"""
插件模板市场 - 预置 ComfyUI 节点开发模板
"""
import re
from pathlib import Path
from typing import Dict, List

# 语言 → 标准目录名映射（中文界面用中文目录，英文界面用英文目录）
# 文件键中的 {node_dir}/{web_dir} 占位符在生成时替换为实际目录名
_LANGUAGE_DIRS = {
    "zh-CN": {"node": "节点", "web": "网页资源", "backend": "后端"},
    "en": {"node": "nodes", "web": "web", "backend": "backend"},
}


def _get_language_dirs(language: str) -> Dict[str, str]:
    """按语言获取标准目录名，未知语言回退中文"""
    return _LANGUAGE_DIRS.get(language, _LANGUAGE_DIRS["zh-CN"])


# 内置模板定义
# 每个模板含 files（中文版）与 files_en（英文版）两套内容，
# 节点代码统一落在 {node_dir}/ 目录，前端 JS 统一落在 {web_dir}/ 目录
BUILTIN_TEMPLATES = [
    {
        "id": "basic_node",
        "name": "基础节点",
        "description": "最简单的 ComfyUI 自定义节点模板，包含一个输入输出节点",
        "category": "入门",
        "files": {
            "__init__.py": '''from .节点.基础节点 import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
WEB_DIRECTORY = "./网页资源"
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
''',
            "{node_dir}/__init__.py": "",
            "{node_dir}/基础节点.py": '''# ═══════════════════════════════════════════════════════
# 【模板类型：基础节点（basic_node）】本文件由 NodeCraft AI 模板生成
# 用户提到「节点 / 输入输出 / 节点分类 / 执行逻辑」时，修改本文件：
#   - 输入参数（文本框、开关等）→ INPUT_TYPES
#   - 输出端口 → RETURN_TYPES / RETURN_NAMES
#   - 右键菜单中的节点分类 → CATEGORY
#   - 节点显示名称 → NODE_DISPLAY_NAME_MAPPINGS
#   - 节点执行逻辑 → execute 方法
# ═══════════════════════════════════════════════════════
class 基础节点_Node:
    """基础自定义节点 - 字符串处理"""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "文本": ("STRING", {"default": "Hello", "multiline": True}),
                "前缀": ("STRING", {"default": "[输出] "}),
                "转大写": ("BOOLEAN", {"default": False}),
            }
        }

    RETURN_TYPES = ("STRING",)
    RETURN_NAMES = ("处理结果",)
    FUNCTION = "execute"
    CATEGORY = "{custom_category}"
    DESCRIPTION = "基础字符串处理节点，支持添加前缀和大写转换。"

    def execute(self, 文本, 前缀, 转大写):
        result = 文本.upper() if 转大写 else 文本
        result = f"{前缀}{result}"
        return (result,)


NODE_CLASS_MAPPINGS = {"基础节点": 基础节点_Node}
NODE_DISPLAY_NAME_MAPPINGS = {"基础节点": "📦 基础节点 (Basic Node)"}
''',
            "requirements.txt": "# 无额外依赖\n",
            "README.md": "# My Basic Node\n\n基础 ComfyUI 自定义节点，支持字符串处理。\n",
        },
        "files_en": {
            "__init__.py": '''from .nodes.basic_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
WEB_DIRECTORY = "./web"
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
''',
            "{node_dir}/__init__.py": "",
            "{node_dir}/basic_node.py": '''# ═══════════════════════════════════════════════════════
# [Template: Basic Node (basic_node)] Generated by NodeCraft AI
# Modify THIS file when the user mentions "node / inputs / outputs / category / logic":
#   - Input widgets (text box, toggle, etc.) -> INPUT_TYPES
#   - Output ports -> RETURN_TYPES / RETURN_NAMES
#   - Node menu category -> CATEGORY
#   - Node display name -> NODE_DISPLAY_NAME_MAPPINGS
#   - Execution logic -> execute method
# ═══════════════════════════════════════════════════════
class BasicNode:
    """Basic custom node - string processing"""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "text": ("STRING", {"default": "Hello", "multiline": True}),
                "prefix": ("STRING", {"default": "[Output] "}),
                "to_upper": ("BOOLEAN", {"default": False}),
            }
        }

    RETURN_TYPES = ("STRING",)
    RETURN_NAMES = ("result",)
    FUNCTION = "execute"
    CATEGORY = "{custom_category}"
    DESCRIPTION = "Basic string processing node with prefix and uppercase options."

    def execute(self, text, prefix, to_upper):
        result = text.upper() if to_upper else text
        result = f"{prefix}{result}"
        return (result,)


NODE_CLASS_MAPPINGS = {"BasicNode": BasicNode}
NODE_DISPLAY_NAME_MAPPINGS = {"BasicNode": "📦 Basic Node"}
''',
            "requirements.txt": "# No extra dependencies\n",
            "README.md": "# My Basic Node\n\nA basic ComfyUI custom node with string processing.\n",
        }
    },
    {
        "id": "image_processor",
        "name": "图像处理节点",
        "description": "图像输入/输出节点模板，包含 PIL 图像处理示例",
        "category": "图像",
        "files": {
            "__init__.py": '''from .节点.图像处理 import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
''',
            "{node_dir}/__init__.py": "",
            "{node_dir}/图像处理.py": '''# ═══════════════════════════════════════════════════════
# 【模板类型：图像处理节点（image_processor）】本文件由 NodeCraft AI 模板生成
# 用户提到「图像处理 / 亮度 / 对比度 / 图像节点」时，修改本文件：
#   - 输入参数与取值范围 → INPUT_TYPES
#   - 图像处理逻辑 → execute 方法（PIL ImageEnhance）
#   - 右键菜单中的节点分类 → CATEGORY
# ═══════════════════════════════════════════════════════
import torch
import numpy as np
from PIL import Image, ImageEnhance


class ImageBrightnessContrast:
    """图像亮度/对比度调整节点"""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "image": ("IMAGE",),
                "brightness": ("FLOAT", {"default": 1.0, "min": 0.0, "max": 3.0, "step": 0.05}),
                "contrast": ("FLOAT", {"default": 1.0, "min": 0.0, "max": 3.0, "step": 0.05}),
            }
        }

    RETURN_TYPES = ("IMAGE",)
    RETURN_NAMES = ("image",)
    FUNCTION = "execute"
    CATEGORY = "Custom/Image"

    def execute(self, image, brightness, contrast):
        # image: [B, H, W, C] torch tensor, float32, 0-1
        results = []
        for i in range(image.shape[0]):
            img_np = (image[i].cpu().numpy() * 255).astype(np.uint8)
            pil_img = Image.fromarray(img_np)

            # 调整亮度
            if brightness != 1.0:
                enhancer = ImageEnhance.Brightness(pil_img)
                pil_img = enhancer.enhance(brightness)

            # 调整对比度
            if contrast != 1.0:
                enhancer = ImageEnhance.Contrast(pil_img)
                pil_img = enhancer.enhance(contrast)

            result_np = np.array(pil_img).astype(np.float32) / 255.0
            results.append(torch.from_numpy(result_np))

        return (torch.stack(results),)


NODE_CLASS_MAPPINGS = {"ImageBrightnessContrast": ImageBrightnessContrast}
NODE_DISPLAY_NAME_MAPPINGS = {"ImageBrightnessContrast": "Image Brightness/Contrast"}
''',
            "requirements.txt": "Pillow>=9.0.0\n",
            "README.md": "# Image Brightness/Contrast\n\n调整图像亮度和对比度的 ComfyUI 节点。\n",
        },
        "files_en": {
            "__init__.py": '''from .nodes.image_processor import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
''',
            "{node_dir}/__init__.py": "",
            "{node_dir}/image_processor.py": '''# ═══════════════════════════════════════════════════════
# [Template: Image Processor (image_processor)] Generated by NodeCraft AI
# Modify THIS file when the user mentions "image / brightness / contrast":
#   - Input widgets and ranges -> INPUT_TYPES
#   - Image processing logic -> execute method (PIL ImageEnhance)
#   - Node menu category -> CATEGORY
# ═══════════════════════════════════════════════════════
import torch
import numpy as np
from PIL import Image, ImageEnhance


class ImageBrightnessContrast:
    """Image brightness/contrast adjustment node"""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "image": ("IMAGE",),
                "brightness": ("FLOAT", {"default": 1.0, "min": 0.0, "max": 3.0, "step": 0.05}),
                "contrast": ("FLOAT", {"default": 1.0, "min": 0.0, "max": 3.0, "step": 0.05}),
            }
        }

    RETURN_TYPES = ("IMAGE",)
    RETURN_NAMES = ("image",)
    FUNCTION = "execute"
    CATEGORY = "Custom/Image"

    def execute(self, image, brightness, contrast):
        # image: [B, H, W, C] torch tensor, float32, 0-1
        results = []
        for i in range(image.shape[0]):
            img_np = (image[i].cpu().numpy() * 255).astype(np.uint8)
            pil_img = Image.fromarray(img_np)

            if brightness != 1.0:
                enhancer = ImageEnhance.Brightness(pil_img)
                pil_img = enhancer.enhance(brightness)

            if contrast != 1.0:
                enhancer = ImageEnhance.Contrast(pil_img)
                pil_img = enhancer.enhance(contrast)

            result_np = np.array(pil_img).astype(np.float32) / 255.0
            results.append(torch.from_numpy(result_np))

        return (torch.stack(results),)


NODE_CLASS_MAPPINGS = {"ImageBrightnessContrast": ImageBrightnessContrast}
NODE_DISPLAY_NAME_MAPPINGS = {"ImageBrightnessContrast": "Image Brightness/Contrast"}
''',
            "requirements.txt": "Pillow>=9.0.0\n",
            "README.md": "# Image Brightness/Contrast\n\nA ComfyUI node to adjust image brightness and contrast.\n",
        }
    },
    {
        "id": "model_loader",
        "name": "模型加载节点",
        "description": "支持加载自定义模型的节点模板，含模型缓存逻辑",
        "category": "模型",
        "files": {
            "__init__.py": '''from .节点.模型加载 import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
''',
            "{node_dir}/__init__.py": "",
            "{node_dir}/模型加载.py": '''# ═══════════════════════════════════════════════════════
# 用户提到「模型加载 / 模型缓存 / 释放模型 / 模型目录」时，修改本文件：
#   - 扫描的模型目录与文件后缀 → CustomModelLoader.INPUT_TYPES
#   - 加载与缓存逻辑 → load_model 方法（_model_cache）
#   - 释放缓存逻辑 → CustomModelUnloader.unload
# ═══════════════════════════════════════════════════════
import os
import logging
import torch
import folder_paths

logger = logging.getLogger(__name__)

# 模型缓存（避免重复加载）
_model_cache = {}


class CustomModelLoader:
    """自定义模型加载节点 - 支持 safetensors/pt 文件"""

    @classmethod
    def INPUT_TYPES(cls):
        # 扫描 models 目录获取可用模型文件
        model_files = []
        models_dir = folder_paths.models_dir
        custom_dir = os.path.join(models_dir, "custom")
        if os.path.exists(custom_dir):
            for f in os.listdir(custom_dir):
                if f.endswith((".safetensors", ".pt", ".pth", ".bin")):
                    model_files.append(f)
        if not model_files:
            model_files = ["none"]

        return {
            "required": {
                "model_name": (model_files, {"default": model_files[0]}),
                "device": (["cuda", "cpu", "auto"], {"default": "auto"}),
            }
        }

    RETURN_TYPES = ("MODEL",)
    RETURN_NAMES = ("model",)
    FUNCTION = "load_model"
    CATEGORY = "Custom/Model"

    def load_model(self, model_name, device):
        if model_name == "none":
            raise ValueError("没有可用的模型文件，请将模型放入 models/custom/ 目录")

        # 检查缓存
        cache_key = f"{model_name}_{device}"
        if cache_key in _model_cache:
            logger.debug(f"使用缓存模型: {model_name}")
            return (_model_cache[cache_key],)

        # 确定设备
        if device == "auto":
            device = "cuda" if torch.cuda.is_available() else "cpu"

        # 加载模型
        model_path = os.path.join(folder_paths.models_dir, "custom", model_name)
        logger.info(f"加载模型: {model_path} -> {device}")

        if model_name.endswith(".safetensors"):
            from safetensors.torch import load_file
            state_dict = load_file(model_path, device=device)
        else:
            state_dict = torch.load(model_path, map_location=device, weights_only=True)

        # 缓存模型
        _model_cache[cache_key] = state_dict
        return (state_dict,)


class CustomModelUnloader:
    """释放已缓存的模型"""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "model": ("MODEL",),
                "clear_cache": ("BOOLEAN", {"default": True}),
            }
        }

    RETURN_TYPES = ()
    FUNCTION = "unload"
    CATEGORY = "Custom/Model"
    OUTPUT_NODE = True

    def unload(self, model, clear_cache):
        if clear_cache:
            _model_cache.clear()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            logger.info("模型缓存已清空")
        return ()


NODE_CLASS_MAPPINGS = {
    "CustomModelLoader": CustomModelLoader,
    "CustomModelUnloader": CustomModelUnloader,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    "CustomModelLoader": "Custom Model Loader",
    "CustomModelUnloader": "Custom Model Unloader",
}
''',
            "requirements.txt": "safetensors>=0.3.0\ntorch>=2.0.0\n",
            "README.md": (
                "# Custom Model Loader\n\n"
                "支持加载 safetensors/pt 模型文件，含缓存逻辑。\n"
                "将模型文件放入 `ComfyUI/models/custom/` 目录即可使用。\n"
            ),
        },
        "files_en": {
            "__init__.py": '''from .nodes.model_loader import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
''',
            "{node_dir}/__init__.py": "",
            "{node_dir}/model_loader.py": '''# ═══════════════════════════════════════════════════════
# [Template: Model Loader (model_loader)] Generated by NodeCraft AI
# Modify THIS file when the user mentions "model loading / cache / unload / model dir":
#   - Scanned model dir and file extensions -> CustomModelLoader.INPUT_TYPES
#   - Loading & caching logic -> load_model method (_model_cache)
#   - Cache release logic -> CustomModelUnloader.unload
# ═══════════════════════════════════════════════════════
import os
import logging
import torch
import folder_paths

logger = logging.getLogger(__name__)

# Model cache (avoid repeated loading)
_model_cache = {}


class CustomModelLoader:
    """Custom model loader node - supports safetensors/pt files"""

    @classmethod
    def INPUT_TYPES(cls):
        # Scan models directory for available model files
        model_files = []
        models_dir = folder_paths.models_dir
        custom_dir = os.path.join(models_dir, "custom")
        if os.path.exists(custom_dir):
            for f in os.listdir(custom_dir):
                if f.endswith((".safetensors", ".pt", ".pth", ".bin")):
                    model_files.append(f)
        if not model_files:
            model_files = ["none"]

        return {
            "required": {
                "model_name": (model_files, {"default": model_files[0]}),
                "device": (["cuda", "cpu", "auto"], {"default": "auto"}),
            }
        }

    RETURN_TYPES = ("MODEL",)
    RETURN_NAMES = ("model",)
    FUNCTION = "load_model"
    CATEGORY = "Custom/Model"

    def load_model(self, model_name, device):
        if model_name == "none":
            raise ValueError("No model files available. Please put models in models/custom/")

        cache_key = f"{model_name}_{device}"
        if cache_key in _model_cache:
            logger.debug(f"Using cached model: {model_name}")
            return (_model_cache[cache_key],)

        if device == "auto":
            device = "cuda" if torch.cuda.is_available() else "cpu"

        model_path = os.path.join(folder_paths.models_dir, "custom", model_name)
        logger.info(f"Loading model: {model_path} -> {device}")

        if model_name.endswith(".safetensors"):
            from safetensors.torch import load_file
            state_dict = load_file(model_path, device=device)
        else:
            state_dict = torch.load(model_path, map_location=device, weights_only=True)

        _model_cache[cache_key] = state_dict
        return (state_dict,)


class CustomModelUnloader:
    """Unload cached models"""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "model": ("MODEL",),
                "clear_cache": ("BOOLEAN", {"default": True}),
            }
        }

    RETURN_TYPES = ()
    FUNCTION = "unload"
    CATEGORY = "Custom/Model"
    OUTPUT_NODE = True

    def unload(self, model, clear_cache):
        if clear_cache:
            _model_cache.clear()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            logger.info("Model cache cleared")
        return ()


NODE_CLASS_MAPPINGS = {
    "CustomModelLoader": CustomModelLoader,
    "CustomModelUnloader": CustomModelUnloader,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    "CustomModelLoader": "Custom Model Loader",
    "CustomModelUnloader": "Custom Model Unloader",
}
''',
            "requirements.txt": "safetensors>=0.3.0\ntorch>=2.0.0\n",
            "README.md": (
                "# Custom Model Loader\n\n"
                "Loads safetensors/pt model files with caching.\n"
                "Put model files into `ComfyUI/models/custom/` to use.\n"
            ),
        }
    },
    {
        "id": "workflow_node",
        "name": "工作流节点",
        "description": "多输入多输出的工作流节点模板，支持条件分支",
        "category": "工作流",
        "files": {
            "__init__.py": '''from .节点.工作流控制 import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
''',
            "{node_dir}/__init__.py": "",
            "{node_dir}/工作流控制.py": '''# ═══════════════════════════════════════════════════════
# 用户提到「条件分支 / 路由 / 开关 / 循环计数」时，修改本文件：
#   - 条件路由逻辑 → ConditionalRouter
#   - 数值开关逻辑 → ValueSwitch
#   - 循环计数逻辑 → LoopCounter
# ═══════════════════════════════════════════════════════
class ConditionalRouter:
    """条件路由节点 - 根据条件将输入路由到不同输出"""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "condition": ("BOOLEAN", {"default": True}),
                "input_a": ("*",),
            },
            "optional": {
                "input_b": ("*",),
            }
        }

    RETURN_TYPES = ("*", "*")
    RETURN_NAMES = ("output_true", "output_false")
    FUNCTION = "route"
    CATEGORY = "Custom/Workflow"

    def route(self, condition, input_a, input_b=None):
        if condition:
            return (input_a, input_b)
        else:
            return (input_b, input_a)


class ValueSwitch:
    """数值开关节点 - 根据索引选择不同输入"""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "select_index": ("INT", {"default": 0, "min": 0, "max": 3}),
                "input_0": ("*",),
            },
            "optional": {
                "input_1": ("*",),
                "input_2": ("*",),
                "input_3": ("*",),
            }
        }

    RETURN_TYPES = ("*",)
    RETURN_NAMES = ("selected",)
    FUNCTION = "switch"
    CATEGORY = "Custom/Workflow"

    def switch(self, select_index, input_0, input_1=None, input_2=None, input_3=None):
        inputs = [input_0, input_1, input_2, input_3]
        index = min(select_index, len(inputs) - 1)
        result = inputs[index]
        if result is None:
            result = input_0  # fallback 到第一个输入
        return (result,)


class LoopCounter:
    """循环计数器 - 配合 ComfyUI 循环使用"""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "start": ("INT", {"default": 0}),
                "end": ("INT", {"default": 10}),
                "step": ("INT", {"default": 1, "min": 1}),
                "current": ("INT", {"default": 0}),
            }
        }

    RETURN_TYPES = ("INT", "INT", "BOOLEAN")
    RETURN_NAMES = ("current_value", "next_value", "is_done")
    FUNCTION = "count"
    CATEGORY = "Custom/Workflow"

    def count(self, start, end, step, current):
        next_val = current + step
        is_done = next_val >= end
        return (current, next_val, is_done)


NODE_CLASS_MAPPINGS = {
    "ConditionalRouter": ConditionalRouter,
    "ValueSwitch": ValueSwitch,
    "LoopCounter": LoopCounter,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    "ConditionalRouter": "Conditional Router",
    "ValueSwitch": "Value Switch",
    "LoopCounter": "Loop Counter",
}
''',
            "requirements.txt": "# 无额外依赖\n",
            "README.md": "# Workflow Nodes\n\n工作流控制节点集合：条件路由、数值开关、循环计数器。\n",
        },
        "files_en": {
            "__init__.py": '''from .nodes.workflow_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
''',
            "{node_dir}/__init__.py": "",
            "{node_dir}/workflow_nodes.py": '''# ═══════════════════════════════════════════════════════
# [Template: Workflow Nodes (workflow_node)] Generated by NodeCraft AI
# Modify THIS file when the user mentions "branch / router / switch / loop counter":
#   - Conditional routing logic -> ConditionalRouter
#   - Value switch logic -> ValueSwitch
#   - Loop counting logic -> LoopCounter
# ═══════════════════════════════════════════════════════
class ConditionalRouter:
    """Conditional router node - routes input to different outputs by condition"""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "condition": ("BOOLEAN", {"default": True}),
                "input_a": ("*",),
            },
            "optional": {
                "input_b": ("*",),
            }
        }

    RETURN_TYPES = ("*", "*")
    RETURN_NAMES = ("output_true", "output_false")
    FUNCTION = "route"
    CATEGORY = "Custom/Workflow"

    def route(self, condition, input_a, input_b=None):
        if condition:
            return (input_a, input_b)
        else:
            return (input_b, input_a)


class ValueSwitch:
    """Value switch node - selects an input by index"""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "select_index": ("INT", {"default": 0, "min": 0, "max": 3}),
                "input_0": ("*",),
            },
            "optional": {
                "input_1": ("*",),
                "input_2": ("*",),
                "input_3": ("*",),
            }
        }

    RETURN_TYPES = ("*",)
    RETURN_NAMES = ("selected",)
    FUNCTION = "switch"
    CATEGORY = "Custom/Workflow"

    def switch(self, select_index, input_0, input_1=None, input_2=None, input_3=None):
        inputs = [input_0, input_1, input_2, input_3]
        index = min(select_index, len(inputs) - 1)
        result = inputs[index]
        if result is None:
            result = input_0  # fallback to the first input
        return (result,)


class LoopCounter:
    """Loop counter - works with ComfyUI loop workflows"""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "start": ("INT", {"default": 0}),
                "end": ("INT", {"default": 10}),
                "step": ("INT", {"default": 1, "min": 1}),
                "current": ("INT", {"default": 0}),
            }
        }

    RETURN_TYPES = ("INT", "INT", "BOOLEAN")
    RETURN_NAMES = ("current_value", "next_value", "is_done")
    FUNCTION = "count"
    CATEGORY = "Custom/Workflow"

    def count(self, start, end, step, current):
        next_val = current + step
        is_done = next_val >= end
        return (current, next_val, is_done)


NODE_CLASS_MAPPINGS = {
    "ConditionalRouter": ConditionalRouter,
    "ValueSwitch": ValueSwitch,
    "LoopCounter": LoopCounter,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    "ConditionalRouter": "Conditional Router",
    "ValueSwitch": "Value Switch",
    "LoopCounter": "Loop Counter",
}
''',
            "requirements.txt": "# No extra dependencies\n",
            "README.md": "# Workflow Nodes\n\nWorkflow control nodes: conditional router, value switch, loop counter.\n",
        }
    },
    {
        "id": "ui_extension",
        "name": "UI 扩展节点",
        "description": "包含前端 JavaScript 扩展的节点模板，支持自定义 Widget",
        "category": "界面",
        "files": {
            "__init__.py": '''from .节点.UI扩展节点 import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
WEB_DIRECTORY = "./网页资源"
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
''',
            "{node_dir}/__init__.py": "",
            "{node_dir}/UI扩展节点.py": '''class ColorPickerNode:
    """颜色选择器节点 - 带有前端自定义 Widget"""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "color_hex": ("STRING", {"default": "#FF0000"}),
                "opacity": ("FLOAT", {"default": 1.0, "min": 0.0, "max": 1.0, "step": 0.01}),
            }
        }

    RETURN_TYPES = ("STRING", "INT", "INT", "INT", "FLOAT")
    RETURN_NAMES = ("hex_color", "red", "green", "blue", "opacity")
    FUNCTION = "parse_color"
    CATEGORY = "Custom/UI"

    def parse_color(self, color_hex, opacity):
        # 解析 hex 颜色
        color_hex = color_hex.lstrip("#")
        if len(color_hex) == 3:
            color_hex = "".join(c * 2 for c in color_hex)
        r = int(color_hex[0:2], 16)
        g = int(color_hex[2:4], 16)
        b = int(color_hex[4:6], 16)
        return (f"#{color_hex.upper()}", r, g, b, opacity)


class TextPreviewNode:
    """文本预览节点 - 在节点上显示文本内容"""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "text": ("STRING", {"forceInput": True}),
            }
        }

    RETURN_TYPES = ("STRING",)
    RETURN_NAMES = ("text",)
    FUNCTION = "preview"
    CATEGORY = "Custom/UI"
    OUTPUT_NODE = True

    def preview(self, text):
        # 返回给前端展示
        return {"ui": {"text": [text]}, "result": (text,)}


NODE_CLASS_MAPPINGS = {
    "ColorPickerNode": ColorPickerNode,
    "TextPreviewNode": TextPreviewNode,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    "ColorPickerNode": "Color Picker",
    "TextPreviewNode": "Text Preview",
}
''',
            "{web_dir}/extensions.js": '''// ═══════════════════════════════════════════════════════
// 【模板类型：UI 扩展，入口类型：基础节点（canvas）】由 NodeCraft AI 模板生成
// 用户提到「自定义 Widget / 颜色选择器 / 文本预览 / 节点界面」时，修改本文件：
//   - 颜色选择器 Widget → ColorPickerNode 分支
//   - 节点上的文本预览 → TextPreviewNode 分支
// 后端节点定义（输入输出/执行逻辑）在 节点/UI扩展节点.py，不在本文件。
// ═══════════════════════════════════════════════════════
import { app } from "../../scripts/app.js";

app.registerExtension({
    name: "Custom.UIExtension",
    async beforeRegisterNodeDef(nodeType, nodeData, app) {
        // 为 ColorPickerNode 添加颜色选择器 Widget
        if (nodeData.name === "ColorPickerNode") {
            const origOnNodeCreated = nodeType.prototype.onNodeCreated;
            nodeType.prototype.onNodeCreated = function () {
                if (origOnNodeCreated) origOnNodeCreated.apply(this, arguments);

                const colorWidget = this.widgets.find(w => w.name === "color_hex");
                if (colorWidget) {
                    // 添加颜色预览
                    const origDraw = colorWidget.draw;
                    colorWidget.draw = function (ctx, node, width, y, height) {
                        if (origDraw) origDraw.apply(this, arguments);
                        // 在 widget 旁绘制颜色预览方块
                        const color = this.value || "#FF0000";
                        ctx.fillStyle = color;
                        ctx.fillRect(width - 30, y + 2, 20, height - 4);
                        ctx.strokeStyle = "#666";
                        ctx.strokeRect(width - 30, y + 2, 20, height - 4);
                    };
                }
            };
        }

        // 为 TextPreviewNode 添加文本展示
        if (nodeData.name === "TextPreviewNode") {
            const origOnExecuted = nodeType.prototype.onExecuted;
            nodeType.prototype.onExecuted = function (message) {
                if (origOnExecuted) origOnExecuted.apply(this, arguments);
                if (message && message.text && message.text[0]) {
                    // 显示预览文本
                    if (!this.previewWidget) {
                        this.previewWidget = this.addWidget("text", "preview", "", () => {}, {
                            multiline: true,
                            inputEl: null,
                        });
                    }
                    this.previewWidget.value = message.text[0].substring(0, 200);
                    this.setSize(this.computeSize());
                }
            };
        }
    },
});
''',
            "requirements.txt": "# 无额外依赖\n",
            "README.md": (
                "# UI Extension Nodes\n\n"
                "包含前端自定义 Widget 的 ComfyUI 节点：\n"
                "- Color Picker: 带颜色预览的选色器\n"
                "- Text Preview: 在节点上显示文本\n"
            ),
        },
        "files_en": {
            "__init__.py": '''from .nodes.ui_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
WEB_DIRECTORY = "./web"
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
''',
            "{node_dir}/__init__.py": "",
            "{node_dir}/ui_nodes.py": '''class ColorPickerNode:
    """Color picker node - with a frontend custom widget"""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "color_hex": ("STRING", {"default": "#FF0000"}),
                "opacity": ("FLOAT", {"default": 1.0, "min": 0.0, "max": 1.0, "step": 0.01}),
            }
        }

    RETURN_TYPES = ("STRING", "INT", "INT", "INT", "FLOAT")
    RETURN_NAMES = ("hex_color", "red", "green", "blue", "opacity")
    FUNCTION = "parse_color"
    CATEGORY = "Custom/UI"

    def parse_color(self, color_hex, opacity):
        # Parse hex color
        color_hex = color_hex.lstrip("#")
        if len(color_hex) == 3:
            color_hex = "".join(c * 2 for c in color_hex)
        r = int(color_hex[0:2], 16)
        g = int(color_hex[2:4], 16)
        b = int(color_hex[4:6], 16)
        return (f"#{color_hex.upper()}", r, g, b, opacity)


class TextPreviewNode:
    """Text preview node - shows text content on the node"""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "text": ("STRING", {"forceInput": True}),
            }
        }

    RETURN_TYPES = ("STRING",)
    RETURN_NAMES = ("text",)
    FUNCTION = "preview"
    CATEGORY = "Custom/UI"
    OUTPUT_NODE = True

    def preview(self, text):
        # Return to frontend for display
        return {"ui": {"text": [text]}, "result": (text,)}


NODE_CLASS_MAPPINGS = {
    "ColorPickerNode": ColorPickerNode,
    "TextPreviewNode": TextPreviewNode,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    "ColorPickerNode": "Color Picker",
    "TextPreviewNode": "Text Preview",
}
''',
            "{web_dir}/extensions.js": '''// ═══════════════════════════════════════════════════════
// [Template: UI Extension, entry type: canvas] Generated by NodeCraft AI
// Modify THIS file when the user mentions "widget / color picker / text preview / node UI":
//   - Color picker widget -> ColorPickerNode branch
//   - Text preview on node -> TextPreviewNode branch
// Backend node definitions (inputs/outputs/logic) live in nodes/ui_nodes.py, not here.
// ═══════════════════════════════════════════════════════
import { app } from "../../scripts/app.js";

app.registerExtension({
    name: "Custom.UIExtension",
    async beforeRegisterNodeDef(nodeType, nodeData, app) {
        // Add a color picker widget to ColorPickerNode
        if (nodeData.name === "ColorPickerNode") {
            const origOnNodeCreated = nodeType.prototype.onNodeCreated;
            nodeType.prototype.onNodeCreated = function () {
                if (origOnNodeCreated) origOnNodeCreated.apply(this, arguments);

                const colorWidget = this.widgets.find(w => w.name === "color_hex");
                if (colorWidget) {
                    // Add a color preview swatch next to the widget
                    const origDraw = colorWidget.draw;
                    colorWidget.draw = function (ctx, node, width, y, height) {
                        if (origDraw) origDraw.apply(this, arguments);
                        const color = this.value || "#FF0000";
                        ctx.fillStyle = color;
                        ctx.fillRect(width - 30, y + 2, 20, height - 4);
                        ctx.strokeStyle = "#666";
                        ctx.strokeRect(width - 30, y + 2, 20, height - 4);
                    };
                }
            };
        }

        // Add text preview to TextPreviewNode
        if (nodeData.name === "TextPreviewNode") {
            const origOnExecuted = nodeType.prototype.onExecuted;
            nodeType.prototype.onExecuted = function (message) {
                if (origOnExecuted) origOnExecuted.apply(this, arguments);
                if (message && message.text && message.text[0]) {
                    if (!this.previewWidget) {
                        this.previewWidget = this.addWidget("text", "preview", "", () => {}, {
                            multiline: true,
                            inputEl: null,
                        });
                    }
                    this.previewWidget.value = message.text[0].substring(0, 200);
                    this.setSize(this.computeSize());
                }
            };
        }
    },
});
''',
            "requirements.txt": "# No extra dependencies\n",
            "README.md": (
                "# UI Extension Nodes\n\n"
                "ComfyUI nodes with frontend custom widgets:\n"
                "- Color Picker: color picker with live preview\n"
                "- Text Preview: shows text on the node\n"
            ),
        }
    },
]


# ─── UI 扩展入口类型代码骨架（entry_type -> {web_dir}/extensions.js 内容）───
ENTRY_TYPE_JS_TEMPLATES = {
    "sidebar": '''// ═══════════════════════════════════════════════════════
// 【入口类型：侧边栏 Tab（sidebar）】由 NodeCraft AI 模板生成
// 用户提到「侧边栏 / 侧边栏 Tab / 侧边栏界面」时，修改本文件的 registerSidebarTab 块：
//   - 侧边栏标题/悬停提示 → title / tooltip
//   - 侧边栏图标 → icon（PrimeVue 图标名，如 pi pi-code）
//   - 侧边栏内容界面 → render 回调（在 container 内构建 DOM）
// ═══════════════════════════════════════════════════════
import { app } from "../../scripts/app.js";

app.registerExtension({
    name: "com.example.{project_name}",
    async setup() {
        // 侧边栏 Tab 注册（用户口中的“侧边栏”即此处）
        app.extensionManager.registerSidebarTab({
            id: "{project_name}-sidebar",
            icon: "pi pi-code",
            title: "{sidebar_title}",
            tooltip: "{sidebar_title}",
            type: "custom",
            render: (container) => {
                container.innerHTML = `<div style="padding:16px;"><h3>{sidebar_title}</h3>` +
                    `<p>\u5728\u6b64\u5904\u6784\u5efa\u4f60\u7684\u4fa7\u8fb9\u680f\u754c\u9762</p></div>`;
            },
        });
    },
});
''',
    "topMenu": '''// ═══════════════════════════════════════════════════════
// 【入口类型：顶部菜单栏（topMenu）】由 NodeCraft AI 模板生成
// 用户提到「顶部菜单 / 菜单栏 / 菜单命令」时，修改本文件的 commands 块：
//   - 菜单显示文字 → label
//   - 点击菜单后执行的逻辑 → function 回调
//   - 新增菜单项 → 在 commands 数组中追加新命令对象
// ═══════════════════════════════════════════════════════
import { app } from "../../scripts/app.js";

app.registerExtension({
    name: "com.example.{project_name}",
    async setup() {
        // \u6ce8\u518c\u9876\u90e8\u83dc\u5355\u547d\u4ee4
        app.registerExtension({
            name: "com.example.{project_name}.commands",
            commands: [
                {
                    id: "{project_name}.action",
                    label: "{menu_label}",
                    function: () => {
                        console.log("\u83dc\u5355\u547d\u4ee4\u5df2\u6267\u884c");
                    },
                },
            ],
        });
    },
});
''',
    "statusBar": '''// ═══════════════════════════════════════════════════════
// 【入口类型：底部状态栏（statusBar）】由 NodeCraft AI 模板生成
// 用户提到「底部状态栏 / 状态栏 / 状态指示器」时，修改本文件：
//   - 状态栏显示文字 → indicator.innerHTML 中的 span 文本
//   - 指示灯颜色/样式 → indicator.style.cssText 与圆点 background
//   - 挂载位置 → .comfyui-body-bottom 选择器
// ═══════════════════════════════════════════════════════
import { app } from "../../scripts/app.js";

app.registerExtension({
    name: "com.example.{project_name}",
    async setup() {
        // \u7b49\u5f85 UI \u52a0\u8f7d\u5b8c\u6bd5\u540e\u6ce8\u5165\u72b6\u6001\u680f\u5143\u7d20
        const statusBar = document.querySelector(".comfyui-body-bottom");
        if (statusBar) {
            const indicator = document.createElement("div");
            indicator.style.cssText = "display:flex;align-items:center;gap:4px;padding:0 8px;font-size:12px;";
            indicator.innerHTML = `<span style="width:6px;height:6px;border-radius:50%;background:#4caf50;"></span>` +
                `<span>{status_label}</span>`;
            statusBar.appendChild(indicator);
        }
    },
});
''',
}

# 入口类型 JS 骨架英文版（英文界面创建时使用）
ENTRY_TYPE_JS_TEMPLATES_EN = {
    "sidebar": '''// ═══════════════════════════════════════════════════════
// [Entry type: Sidebar Tab (sidebar)] Generated by NodeCraft AI
// Modify the registerSidebarTab block when the user mentions "sidebar / sidebar tab":
//   - Sidebar title/tooltip -> title / tooltip
//   - Sidebar icon -> icon (PrimeVue icon name, e.g. pi pi-code)
//   - Sidebar content UI -> render callback (build DOM inside container)
// ═══════════════════════════════════════════════════════
import { app } from "../../scripts/app.js";

app.registerExtension({
    name: "com.example.{project_name}",
    async setup() {
        // Sidebar tab registration
        app.extensionManager.registerSidebarTab({
            id: "{project_name}-sidebar",
            icon: "pi pi-code",
            title: "{sidebar_title}",
            tooltip: "{sidebar_title}",
            type: "custom",
            render: (container) => {
                container.innerHTML = `<div style="padding:16px;"><h3>{sidebar_title}</h3>` +
                    `<p>Build your sidebar UI here</p></div>`;
            },
        });
    },
});
''',
    "topMenu": '''// ═══════════════════════════════════════════════════════
// [Entry type: Top Menu (topMenu)] Generated by NodeCraft AI
// Modify the commands block when the user mentions "top menu / menu bar / menu command":
//   - Menu display text -> label
//   - Logic executed on click -> function callback
//   - Add menu item -> append a new command object to the commands array
// ═══════════════════════════════════════════════════════
import { app } from "../../scripts/app.js";

app.registerExtension({
    name: "com.example.{project_name}",
    async setup() {
        // Register top menu commands
        app.registerExtension({
            name: "com.example.{project_name}.commands",
            commands: [
                {
                    id: "{project_name}.action",
                    label: "{menu_label}",
                    function: () => {
                        console.log("Menu command executed");
                    },
                },
            ],
        });
    },
});
''',
    "statusBar": '''// ═══════════════════════════════════════════════════════
// [Entry type: Status Bar (statusBar)] Generated by NodeCraft AI
// Modify THIS file when the user mentions "status bar / bottom bar / status indicator":
//   - Status bar text -> span text inside indicator.innerHTML
//   - Indicator light color/style -> indicator.style.cssText and dot background
//   - Mount position -> .comfyui-body-bottom selector
// ═══════════════════════════════════════════════════════
import { app } from "../../scripts/app.js";

app.registerExtension({
    name: "com.example.{project_name}",
    async setup() {
        // Inject status bar element after the UI is ready
        const statusBar = document.querySelector(".comfyui-body-bottom");
        if (statusBar) {
            const indicator = document.createElement("div");
            indicator.style.cssText = "display:flex;align-items:center;gap:4px;padding:0 8px;font-size:12px;";
            indicator.innerHTML = `<span style="width:6px;height:6px;border-radius:50%;background:#4caf50;"></span>` +
                `<span>{status_label}</span>`;
            statusBar.appendChild(indicator);
        }
    },
});
''',
}

# 入口类型中文标签
ENTRY_TYPE_LABELS = {
    "canvas": "\u57fa\u7840\u8282\u70b9",
    "sidebar": "\u4fa7\u8fb9\u680f Tab",
    "topMenu": "\u9876\u90e8\u83dc\u5355\u680f",
    "statusBar": "\u5e95\u90e8\u72b6\u6001\u680f",
}

# 入口类型英文标签
ENTRY_TYPE_LABELS_EN = {
    "canvas": "Basic Node",
    "sidebar": "Sidebar Tab",
    "topMenu": "Top Menu",
    "statusBar": "Status Bar",
}

# ─── README 功能对照表条目（供对话智能体理解用户口语术语 → 代码位置）───
# 入口类型 → 对照说明（用户可能的叫法 | 对应文件与代码位置）
ENTRY_TYPE_README_ROWS = {
    "canvas": "| 节点 / 自定义 Widget / 节点界面 | `网页资源/extensions.js`（前端 Widget）与 `节点/UI扩展节点.py`（节点定义） |",
    "sidebar": "| 侧边栏 / 侧边栏 Tab / 侧边栏界面 | `网页资源/extensions.js` 中的 `registerSidebarTab` 块（title=标题，render=界面内容） |",
    "topMenu": "| 顶部菜单栏 / 菜单 / 菜单命令 | `网页资源/extensions.js` 中的 `commands` 块（label=菜单文字，function=点击逻辑） |",
    "statusBar": "| 底部状态栏 / 状态栏 / 状态指示器 | `网页资源/extensions.js` 中 `.comfyui-body-bottom` 相关代码（innerHTML=显示文字） |",
}

# 勾选项 → 对照说明
OPTION_README_ROWS = {
    "shortcuts": "| 快捷键与全局事件 / 快捷键 / 键盘事件 | `网页资源/extensions.js` 末尾【勾选项：快捷键与全局事件】注释标记的 `keydown` 监听块 |",
    "settings": "| 设置面板 / 设置项 / 用户配置 | `网页资源/extensions.js` 末尾【勾选项：设置面板】注释标记的 `addSetting` 调用（注册进 ComfyUI 自带设置对话框） |",
}

# 非 UI 扩展模板 → 对照说明
TEMPLATE_README_ROWS = {
    "basic_node": "| 节点 / 输入输出 / 节点分类 / 执行逻辑 | `节点/基础节点.py`（INPUT_TYPES=输入，RETURN_TYPES=输出，CATEGORY=分类，execute=逻辑） |",
    "image_processor": "| 图像处理 / 亮度 / 对比度 | `节点/图像处理.py` 的 `execute` 方法（PIL ImageEnhance） |",
    "model_loader": "| 模型加载 / 模型缓存 / 释放模型 | `节点/模型加载.py`（load_model=加载与缓存，unload=释放） |",
    "workflow_node": "| 条件分支 / 路由 / 开关 / 循环计数 | `节点/工作流控制.py`（ConditionalRouter / ValueSwitch / LoopCounter） |",
}

# ─── 英文界面对照表（路径与文案均用英文）───
ENTRY_TYPE_README_ROWS_EN = {
    "canvas": "| node / custom widget / node UI | `web/extensions.js` (frontend widget) & `nodes/ui_nodes.py` (node definitions) |",
    "sidebar": "| sidebar / sidebar tab | the `registerSidebarTab` block in `web/extensions.js` (title, render=UI content) |",
    "topMenu": "| top menu / menu bar / menu command | the `commands` block in `web/extensions.js` (label, function=click logic) |",
    "statusBar": "| status bar / bottom bar / indicator | the `.comfyui-body-bottom` code in `web/extensions.js` (innerHTML=text) |",
}

OPTION_README_ROWS_EN = {
    "shortcuts": "| shortcuts / hotkeys / keyboard events | the `keydown` block marked [Option: Shortcuts] at the end of `web/extensions.js` |",
    "settings": "| settings panel / preferences | the `addSetting` call marked [Option: Settings] at the end of `web/extensions.js` |",
}

TEMPLATE_README_ROWS_EN = {
    "basic_node": "| node / inputs / outputs / category / logic | `nodes/basic_node.py` (INPUT_TYPES, RETURN_TYPES, CATEGORY, execute) |",
    "image_processor": "| image / brightness / contrast | the `execute` method in `nodes/image_processor.py` (PIL ImageEnhance) |",
    "model_loader": "| model loading / cache / unload | `nodes/model_loader.py` (load_model, unload) |",
    "workflow_node": "| branch / router / switch / loop counter | `nodes/workflow_nodes.py` (ConditionalRouter / ValueSwitch / LoopCounter) |",
}


def _构建功能对照表(template_id: str, entry_type: str, options: list, language: str = "zh-CN") -> str:
    """生成 README 末尾的功能对照表，帮助对话智能体把用户口语术语映射到代码位置"""
    _is_en = language == "en"
    rows = []
    if template_id == "ui_extension":
        row = (ENTRY_TYPE_README_ROWS_EN if _is_en else ENTRY_TYPE_README_ROWS).get(entry_type)
        if row:
            rows.append(row)
        for opt in options:
            row = (OPTION_README_ROWS_EN if _is_en else OPTION_README_ROWS).get(opt)
            if row:
                rows.append(row)
    else:
        row = (TEMPLATE_README_ROWS_EN if _is_en else TEMPLATE_README_ROWS).get(template_id)
        if row:
            rows.append(row)

    if not rows:
        return ""

    if _is_en:
        return (
            "\n## Feature Map (AI Guide)\n\n"
            "> This project was created from a NodeCraft AI template. The table below maps common\n"
            "> user terms to files and code locations. Locate via this table first, then confirm\n"
            "> scope with the [Template/Entry/Option] comment markers in the code.\n\n"
            "| What the user may say | File and code location |\n"
            "| --- | --- |\n"
            + "\n".join(rows) + "\n"
        )
    return (
        "\n## 功能对照表（AI 修改指引）\n\n"
        "> 本项目由 NodeCraft AI 模板创建。下表将用户常用叫法映射到对应文件与代码位置，\n"
        "> AI 助手修改功能时请先按此表定位，再结合代码内【模板类型/入口类型/勾选项】注释标记确认范围。\n\n"
        "| 用户可能的叫法 | 对应文件与代码位置 |\n"
        "| --- | --- |\n"
        + "\n".join(rows) + "\n"
    )

# options 附加代码块（追加到 {web_dir}/extensions.js 末尾）
OPTION_JS_SNIPPETS = {
    "shortcuts": '''
// ═══════════════════════════════════════════════════════
// 【勾选项：快捷键与全局事件（shortcuts）】创建项目时勾选生成
// 用户提到「快捷键 / 键盘事件 / 全局事件」时，修改下方代码块：
//   - 按键组合 → if 条件中的 ctrlKey/shiftKey/key 判断
//   - 触发后的逻辑 → if 块内部
// ═══════════════════════════════════════════════════════
document.addEventListener("keydown", (e) => {
    if (e.ctrlKey && e.shiftKey && e.key === "P") {
        e.preventDefault();
        console.log("\u81ea\u5b9a\u4e49\u5feb\u6377\u952e\u89e6\u53d1");
        // \u5728\u6b64\u5904\u6dfb\u52a0\u5feb\u6377\u952e\u903b\u8f91
    }
});
''',
    "settings": '''
// ═══════════════════════════════════════════════════════
// 【勾选项：设置面板（settings）】创建项目时勾选生成
// 用户提到「设置面板 / 设置项 / 用户配置 / 偏好设置」时，修改下方代码块：
// 本质是调用 ComfyUI 官方 Settings API，把设置项注册进 ComfyUI 自带设置对话框（齿轮图标），
// 持久化由 ComfyUI 自动完成：
//   - 设置项名称 → name；控件类型 → type（boolean/text/number/combo/slider）
//   - 默认值 → defaultValue；变更回调 → onChange
//   - 新增设置项 → 再调用一次 addSetting（id 需唯一）
// ═══════════════════════════════════════════════════════
app.ui?.settings?.addSetting({
    id: "{project_name}.my_setting",
    name: "\u6211\u7684\u8bbe\u7f6e\u9879",
    type: "boolean",
    defaultValue: true,
    onChange: (value) => { console.log("\u8bbe\u7f6e\u5df2\u66f4\u6539:", value); },
});
''',
}

# 勾选项附加代码块英文版
OPTION_JS_SNIPPETS_EN = {
    "shortcuts": '''
// ═══════════════════════════════════════════════════════
// [Option: Shortcuts & global events (shortcuts)] Generated when checked at creation
// Modify the block below when the user mentions "shortcut / hotkey / keyboard event":
//   - Key combination -> ctrlKey/shiftKey/key checks in the if condition
//   - Triggered logic -> inside the if block
// ═══════════════════════════════════════════════════════
document.addEventListener("keydown", (e) => {
    if (e.ctrlKey && e.shiftKey && e.key === "P") {
        e.preventDefault();
        console.log("Custom shortcut triggered");
        // Add shortcut logic here
    }
});
''',
    "settings": '''
// ═══════════════════════════════════════════════════════
// [Option: Settings panel (settings)] Generated when checked at creation
// Modify the block below when the user mentions "settings / preferences":
// This calls the official ComfyUI Settings API to register items into the built-in
// settings dialog (gear icon); persistence is handled by ComfyUI automatically:
//   - Setting name -> name; control type -> type (boolean/text/number/combo/slider)
//   - Default value -> defaultValue; change callback -> onChange
//   - Add setting -> call addSetting again (id must be unique)
// ═══════════════════════════════════════════════════════
app.ui?.settings?.addSetting({
    id: "{project_name}.my_setting",
    name: "My Setting",
    type: "boolean",
    defaultValue: true,
    onChange: (value) => { console.log("Setting changed:", value); },
});
''',
}


class TemplateMarket:
    """模板市场管理器"""

    def __init__(self, custom_nodes_dir: Path):
        self.custom_nodes_dir = custom_nodes_dir

    def list_templates(self) -> List[Dict]:
        """获取所有可用模板"""
        return [
            {"id": t["id"], "name": t["name"], "description": t["description"], "category": t["category"]}
            for t in BUILTIN_TEMPLATES
        ]

    def get_template(self, template_id: str) -> Dict:
        """获取模板详情"""
        for t in BUILTIN_TEMPLATES:
            if t["id"] == template_id:
                return t
        return None

    def create_from_template(self, template_id: str, project_name: str,
                             entry_type: str = "canvas", options: list = None,
                             custom_names: dict = None, language: str = "zh-CN") -> Dict:
        """从模板创建新项目

        entry_type: UI 扩展入口类型（canvas/sidebar/topMenu/statusBar），仅对 ui_extension 模板生效
        options: 附加能力列表（如 shortcuts/settings），在生成的 JS 中追加对应代码块
        custom_names: 用户自定义名称，根据 entry_type 包含不同键：
            - canvas: {"category": "节点分类名称"}
            - sidebar: {"sidebar_title": "侧边栏显示名称"}
            - topMenu: {"menu_label": "菜单显示名称"}
            - statusBar: {"status_label": "状态栏显示名称"}
        language: 界面语言（zh-CN/en），决定目录名与生成内容语言：
            - zh-CN: 节点/、网页资源/、后端/ + 中文注释与显示名
            - en: nodes/、web/、backend/ + 英文注释与显示名
        """
        if options is None:
            options = []
        if custom_names is None:
            custom_names = {}

        template = self.get_template(template_id)
        if not template:
            return {"success": False, "message": f"模板 '{template_id}' 不存在"}

        # 验证项目名
        if not re.match(r'^[a-zA-Z0-9_-]+$', project_name):
            return {"success": False, "message": "项目名称只能包含字母、数字、下划线和连字符"}

        if len(project_name) > 128:
            return {"success": False, "message": "项目名称过长（最大128字符）"}

        target_dir = self.custom_nodes_dir / project_name
        if target_dir.exists():
            return {"success": False, "message": f"目录 '{project_name}' 已存在"}

        # 按语言选择模板内容（英文界面优先用英文版，缺失时回退中文版）
        _is_en = language == "en"
        _dirs = _get_language_dirs(language)
        node_dir, web_dir = _dirs["node"], _dirs["web"]
        files = dict(template.get("files_en" if _is_en else "files") or template["files"])

        # 仅 ui_extension 模板根据 entry_type/options 生成差异化 JS
        if template_id == "ui_extension":
            _js_templates = ENTRY_TYPE_JS_TEMPLATES_EN if _is_en else ENTRY_TYPE_JS_TEMPLATES
            js_content = _js_templates.get(entry_type)
            if js_content is not None:
                # sidebar/topMenu/statusBar 使用差异化骨架替换默认 JS
                js_content = js_content.replace("{project_name}", project_name)
                # 替换自定义显示名称占位符（默认值随语言切换）
                if _is_en:
                    js_content = js_content.replace("{sidebar_title}", custom_names.get("sidebar_title", "My Plugin"))
                    js_content = js_content.replace("{menu_label}", custom_names.get("menu_label", "My Command"))
                    js_content = js_content.replace("{status_label}", custom_names.get("status_label", "My Status"))
                else:
                    js_content = js_content.replace("{sidebar_title}", custom_names.get("sidebar_title", "我的插件"))
                    js_content = js_content.replace("{menu_label}", custom_names.get("menu_label", "我的命令"))
                    js_content = js_content.replace("{status_label}", custom_names.get("status_label", "我的状态"))
            else:
                # canvas 或未知类型：使用模板自带的默认 JS（键仍为占位符形式）
                js_content = files.get("{web_dir}/extensions.js", "")

            # 根据 options 在 JS 末尾追加附加代码块
            _snippets = OPTION_JS_SNIPPETS_EN if _is_en else OPTION_JS_SNIPPETS
            for opt in options:
                snippet = _snippets.get(opt)
                if snippet:
                    js_content += snippet.replace("{project_name}", project_name)

            if js_content:
                files["{web_dir}/extensions.js"] = js_content

        # basic_node 模板：替换自定义 CATEGORY（默认分类名随语言切换）
        if template_id == "basic_node":
            _default_category = "🔧 Custom Tools/Basic" if _is_en else "🔧 自定义工具/基础处理"
            custom_category = custom_names.get("category", _default_category)
            for _key in list(files.keys()):
                if _key.endswith(("基础节点.py", "basic_node.py")):
                    files[_key] = files[_key].replace("{custom_category}", custom_category)

        # README 末尾追加功能对照表，让对话智能体读取项目时能理解用户口语术语
        对照表 = _构建功能对照表(template_id, entry_type, options, language)
        if 对照表:
            files["README.md"] = files.get("README.md", "") + 对照表

        # 创建项目目录和文件
        target_dir.mkdir(parents=True)

        # ── 创建标准目录结构（与"自定义插件"保持一致，目录名随语言切换）──
        (target_dir / node_dir).mkdir(exist_ok=True)
        (target_dir / web_dir).mkdir(exist_ok=True)
        # 侧边栏/菜单/状态栏等 UI 扩展类模板额外创建后端目录，放置后端功能文件
        if template_id == "ui_extension":
            (target_dir / _dirs["backend"]).mkdir(exist_ok=True)

        for file_path, content in files.items():
            # 替换目录占位符为实际目录名
            real_path = file_path.replace("{node_dir}", node_dir).replace("{web_dir}", web_dir)
            full_path = target_dir / real_path
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content, encoding='utf-8')

        _labels = ENTRY_TYPE_LABELS_EN if _is_en else ENTRY_TYPE_LABELS
        entry_type_label = _labels.get(entry_type, entry_type)
        if _is_en:
            message = f"Project '{project_name}' created (entry type: {entry_type_label})"
        else:
            message = f"项目 '{project_name}' 已创建（入口类型：{entry_type_label}）"
        return {
            "success": True,
            "message": message,
            "path": str(target_dir),
            "entry_type": entry_type,
            "options": options,
        }
